language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Debug

    - os: linux
      dist: trusty
      sudo: required
      env: TYPE=Release
      
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - TYPE=Release

    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
        - TYPE=Debug



before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install libssl-dev libgmp-dev build-essential cmake git -y
  - git clone https://github.com/emp-toolkit/emp-readme.git
  - bash ./emp-readme/scripts/install_relic.sh
  - bash ./emp-readme/scripts/install_emp-tool.sh
  - bash ./emp-readme/scripts/install_emp-ot.sh

addons:

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug . && make 
  - ./run ./bin/bench_mal2pc 12345